const api = `${location.protocol}//${location.hostname}:3100/api/v1`;
let token = sessionStorage.getItem('procurex-token'), user = null, kind = null, bills = [], selectedBill = null, detail = null, previewData = null;
const $ = (id) => document.getElementById(id);
const kinds = {
  store: { label: '门店账单', path: 'store-statements', roles: ['ADMIN','HQ_FINANCE','STORE','STORE_FINANCE'], object: '门店' },
  supplier: { label: '供应商周期总单', path: 'supplier-statements', roles: ['ADMIN','HQ_FINANCE','SUPPLIER'], object: '供应商' },
  supplierStore: { label: '供应商分店单', path: 'supplier-store-statements', roles: ['ADMIN','HQ_FINANCE','SUPPLIER'], object: '门店' },
  direct: { label: '直接账期', path: 'direct-statements', roles: ['ADMIN','HQ_FINANCE','STORE','STORE_FINANCE','SUPPLIER'], object: '门店 / 供应商' },
};
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = (n) => `¥${Number(n || 0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date = (s) => s ? new Date(`${s.slice(0,10)}T00:00:00`).toLocaleDateString('zh-CN') : '—';
async function call(path, options={}) {
  const response = await fetch(`${api}${path}`, { ...options, headers: { ...(options.body instanceof ArrayBuffer ? {} : {'Content-Type':'application/json'}), ...(token ? {Authorization:`Bearer ${token}`} : {}), ...options.headers } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.message || body.error?.message || `请求失败（${response.status}）`);
  return body.data ?? body;
}
function notice(message) { $('notice').textContent=message; $('notice').classList.remove('hidden'); }
function setIdentity() {
  $('identity').textContent = user ? `${user.displayName} · ${(user.roles||[]).join(', ')}` : '已登录';
  $('login').classList.add('hidden'); $('workspace').classList.remove('hidden'); $('logout').classList.remove('hidden');
  const available = Object.entries(kinds).filter(([,v]) => v.roles.some(r => (user.roles||[]).includes(r)));
  $('bill-tabs').innerHTML = available.map(([key,v]) => `<button class="tab ${key===kind?'active':''}" data-kind="${key}">${v.label}</button>`).join('');
  if (!available.some(([key])=>key===kind)) kind=available[0]?.[0] ?? null;
  $('bill-tabs').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{kind=b.dataset.kind;selectedBill=null;renderTabs();loadBills();}));
  const company=(user.roles||[]).some(r=>['ADMIN','HQ_FINANCE'].includes(r));
  $('store-filter').classList.toggle('hidden',!company || !['supplierStore','direct'].includes(kind));
  $('supplier-filter').classList.toggle('hidden',!company || !['store','supplierStore','direct'].includes(kind));
  renderTabs();
}
function renderTabs(){ $('bill-tabs').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.kind===kind)); }
async function loadMe(){ if(!token)return; try{const d=await call('/me');user=d.user||d;setIdentity();await loadBills();await loadPayments();}catch{token=null;sessionStorage.removeItem('procurex-token');$('workspace').classList.add('hidden');$('login').classList.remove('hidden');} }
async function login(event){event.preventDefault();$('login-error').textContent='';const f=new FormData(event.currentTarget);try{const d=await call('/auth/login',{method:'POST',body:JSON.stringify({username:f.get('username'),password:f.get('password'),client:'WEB'})});token=d.accessToken;user=d.user;sessionStorage.setItem('procurex-token',token);setIdentity();await loadBills();await loadPayments();}catch(e){$('login-error').textContent=e.message;}}
async function loadBills(){if(!kind)return;const meta=kinds[kind],q=new URLSearchParams();if($('cycle').value)q.set('cycle',$('cycle').value);if($('status').value)q.set('settlementStatus',$('status').value);if($('storeId').value)q.set('storeId',$('storeId').value);if($('supplierId').value)q.set('supplierId',$('supplierId').value);$('notice').classList.add('hidden');try{bills=await call(`/${meta.path}?${q}`);renderBills();}catch(e){notice(e.message);}}
function renderBills(){ $('count').textContent=`${bills.length} 张`; $('empty').classList.toggle('hidden',!!bills.length); $('bills').innerHTML=bills.map((b,i)=>`<tr><td><strong>${esc(b.cycle)} · ${date(b.periodStart)} — ${date(b.periodEndExclusive)}</strong></td><td>${esc(b.supplierName||b.supplierId||'—')}</td><td>${esc(b.storeName||b.storeId||`${b.storeCount??''} 家门店`)}</td><td class="money">${money(b.goodsAmount)}</td><td class="money">${money(b.freightAmount)}</td><td class="money">${money(b.adjustmentAmount)}</td><td class="money">${money(b.confirmedPaidAmount)}</td><td class="money">${money(b.pendingPaymentAmount)}</td><td class="money"><strong>${money(b.payableAmount)}</strong></td><td><span class="tag ${b.settlementStatus==='SETTLED'?'tag-settled':'tag-open'}">${b.settlementStatus==='SETTLED'?'已结清':'未结清'}</span></td><td><button class="payment-button" data-open="${i}">明细</button></td></tr>`).join('');$('bills').querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openBill(Number(b.dataset.open)))); }
async function openBill(index){selectedBill=bills[index];detail=null;previewData=null;$('preview-box').classList.add('hidden');try{detail=await call(`/${kinds[kind].path}/${encodeURIComponent(selectedBill.id)}`);renderDetail();}catch(e){notice(e.message);}}
function lineRows(lines){const rows=lines.map(line=>{const amount=Number(line.totalAmount||0);return `<tr><td class="choose-col"><input type="checkbox" data-item="${esc(line.settlementItemId)}" data-version="${line.sourceRevision}" data-amount="${line.totalAmount}" ${amount>0?'':'disabled'}></td><td><span class="line-name">${esc(line.supplierOrderNo||line.supplierOrderId)}</span></td><td>${date(line.firstShippedAt)}</td><td class="money">${money(line.goodsAmount)}</td><td class="money">${money(line.freightAmount)}</td><td class="money">—</td><td class="money">${money(line.totalAmount)}</td></tr>`;});for(const item of detail.adjustmentItems||[])rows.push(`<tr><td class="choose-col"><input type="checkbox" data-item="${esc(item.settlementItemId)}" data-amount="${item.amount}"></td><td><span class="line-name">价格调整</span></td><td>本期</td><td class="money">—</td><td class="money">—</td><td class="money">调整</td><td class="money">${money(item.amount)}</td></tr>`);return rows.join('');}
function renderDetail(){const lines=detail.lines||[];$('detail').classList.remove('hidden');$('detail-subtitle').textContent=`${date(detail.periodStart)} — ${date(detail.periodEndExclusive)} · ${lines.length} 个来源项 · ${money(detail.totalAmount)}`;$('lines').innerHTML=lineRows(lines);const roles=user.roles||[],canPay=roles.some(r=>['ADMIN','HQ_FINANCE','STORE','STORE_FINANCE'].includes(r));$('payment-actions').classList.toggle('hidden',!canPay);$('business-date').value=new Date().toISOString().slice(0,10);$('lines').querySelectorAll('input[type=checkbox]').forEach(c=>c.addEventListener('change',updateSelection));$('preview').onclick=previewPayment;$('register').onclick=registerPayment;updateSelection();}
function selectedIds(){return [...$('lines').querySelectorAll('input:checked')].map(e=>e.dataset.item);}
function updateSelection(){const ids=selectedIds();const total=[...$('lines').querySelectorAll('input:checked')].reduce((n,e)=>n+Number(e.dataset.amount),0);$('selected-amount').textContent=money(total);previewData=null;$('register').disabled=true;$('preview-box').classList.add('hidden');$('preview').disabled=!ids.length;}
async function previewPayment(){try{const ids=selectedIds();previewData=await call('/payment-records/preview',{method:'POST',body:JSON.stringify({settlementItemIds:ids})});$('selected-amount').textContent=money(previewData.totalPayableAmount);$('preview-box').textContent=`付款方向：${previewData.direction} · 通道：${previewData.channel} · 可登记 ${money(previewData.totalPayableAmount)}${previewData.blockedItems?.length?` · 阻断 ${previewData.blockedItems.map(x=>x.message).join('；')}`:''}`;$('preview-box').classList.remove('hidden');$('register').disabled=!!previewData.blockedItems?.length||!previewData.items?.length;}catch(e){notice(e.message);}}
async function uploadProof(file){if(!file)throw new Error('请先选择付款凭证');const session=await call('/files/upload-sessions',{method:'POST',body:JSON.stringify({purpose:'PAYMENT',filename:file.name,mimeType:file.type,sizeBytes:file.size})});const response=await fetch(`${api}/files/${session.id}/content`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/octet-stream','X-Upload-Token':session.uploadToken},body:file});if(!response.ok)throw new Error('凭证上传失败');await call(`/files/${session.id}/complete`,{method:'POST'});return session.id;}
async function registerPayment(){const button=$('register');button.disabled=true;try{if(!previewData)throw new Error('请先预览付款');const evidenceFileId=await uploadProof($('proof').files[0]);const idempotencyKey=`web-payment-${crypto.randomUUID()}`;const result=await call('/payment-records',{method:'POST',headers:{'Idempotency-Key':idempotencyKey},body:JSON.stringify({direction:previewData.direction,businessDate:$('business-date').value,items:previewData.items.map(i=>({settlementItemId:i.settlementItemId,expectedVersion:i.sourceVersion,expectedAmount:i.payableAmount})),evidenceFileIds:[evidenceFileId]})});$('proof').value='';notice(`付款 ${result.paymentNo} 已登记，等待收款方确认。`);await loadBills();await loadPayments();}catch(e){notice(e.message);button.disabled=false;}}
async function loadPayments(){try{const rows=await call('/payment-records');const visible=rows||[];$('payments-empty').classList.toggle('hidden',!!visible.length);$('payments').innerHTML=visible.map(p=>{const confirmable=p.status==='PENDING'&&(user.roles||[]).some(r=>['ADMIN','HQ_FINANCE','SUPPLIER'].includes(r));return `<tr><td><strong>${esc(p.paymentNo)}</strong></td><td>${esc(p.direction)}</td><td>${date(p.businessDate)}</td><td class="money">${money(p.amount)}</td><td><span class="tag ${p.status==='CONFIRMED'?'tag-settled':'tag-open'}">${esc(p.status)}</span></td><td>${(p.evidenceFileIds||[]).map(id=>`<a class="proof-link" target="_blank" href="${api}/files/${encodeURIComponent(id)}/download" data-file="${esc(id)}">凭证</a>`).join(' ')||'—'}</td><td>${confirmable?`<button class="payment-button" data-confirm="${esc(p.id)}" data-version="${p.version}">确认收款</button>`:''}</td></tr>`;}).join('');$('payments').querySelectorAll('[data-file]').forEach(a=>a.addEventListener('click',async e=>{e.preventDefault();try{const r=await fetch(`${api}/files/${encodeURIComponent(a.dataset.file)}/download`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('无权下载凭证');const u=URL.createObjectURL(await r.blob());window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),30000);}catch(err){notice(err.message);}}));$('payments').querySelectorAll('[data-confirm]').forEach(b=>b.addEventListener('click',()=>confirmPayment(b.dataset.confirm,Number(b.dataset.version))));}catch(e){notice(e.message);}}
async function confirmPayment(id,version){try{await call(`/payment-records/${id}/confirm`,{method:'POST',headers:{'Idempotency-Key':`web-confirm-${crypto.randomUUID()}`},body:JSON.stringify({expectedVersion:version})});notice('收款确认完成。');await loadPayments();await loadBills();}catch(e){notice(e.message);}}
$('login-form').addEventListener('submit',login);$('refresh').addEventListener('click',loadBills);$('refresh-payments').addEventListener('click',loadPayments);$('close-detail').addEventListener('click',()=>$('detail').classList.add('hidden'));$('logout').addEventListener('click',async()=>{try{await call('/auth/logout',{method:'POST'});}catch{}token=null;user=null;sessionStorage.removeItem('procurex-token');$('workspace').classList.add('hidden');$('login').classList.remove('hidden');$('logout').classList.add('hidden');$('identity').textContent='未登录';});
showLogin();function showLogin(){if(token)loadMe();else{$('login').classList.remove('hidden');$('workspace').classList.add('hidden');}}
