import assert from 'node:assert/strict';
import test from 'node:test';
import type { AddressInfo } from 'node:net';
import { NestFactory } from '@nestjs/core';
import { PrismaPg } from '@prisma/adapter-pg';
import { AppModule } from '../../apps/api/src/app.module.js';
import { ApiExceptionFilter } from '../../apps/api/src/common/api-exception.filter.js';
import { ResponseEnvelopeInterceptor } from '../../apps/api/src/common/response-envelope.interceptor.js';
import { PrismaClient, type Supplier, type Product } from '../../packages/backend/generated/prisma/client.js';
import { hashPassword } from '../../packages/domain/src/password.js';

test('purchaser draft preview, item edits and assignments guard approved prices and replay exact submissions', async () => {
  const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL ?? 'postgresql://procurex:procurex_local_only@127.0.0.1:55438/procurex?schema=public' }) });
  const prefix = `ITPW${Date.now()}`;
  const app = await NestFactory.create(AppModule, { logger: false });
  app.setGlobalPrefix('api/v1'); app.useGlobalFilters(new ApiExceptionFilter()); app.useGlobalInterceptors(new ResponseEnvelopeInterceptor());
  try {
    await app.listen(0, '127.0.0.1');
    const base = `http://127.0.0.1:${(app.getHttpServer().address() as AddressInfo).port}/api/v1`;
    const role = await db.role.upsert({ where: { code: 'PURCHASER' }, update: {}, create: { code: 'PURCHASER', name: 'Purchaser' } });
    const user = await db.user.create({ data: { username: prefix, displayName: 'Purchaser fixture', passwordHash: await hashPassword('correct-password'), roles: { create: { roleId: role.id } } } });
    const login = await fetch(`${base}/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username: prefix, password: 'correct-password', client: 'WEB' }) });
    assert.equal(login.status, 201); const token = (await login.json() as any).data.accessToken;
    const call = async (path: string, method = 'GET', body?: object, key?: string) => {
      const response = await fetch(`${base}${path}`, { method, headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json', ...(key ? { 'idempotency-key': key } : {}) }, body: body ? JSON.stringify(body) : undefined });
      return { status: response.status, body: await response.json() as any };
    };
    const store = await db.store.create({ data: { code: prefix, name: 'Draft store' } });
    await db.storeAccount.create({ data: { storeId: store.id } });
    const category = await db.category.create({ data: { code: prefix, name: 'Draft category' } });
    const unit = await db.unit.create({ data: { code: prefix, name: 'piece' } });
    const template = await db.orderTemplate.create({ data: { code: prefix, name: prefix, tag: 'Draft' } });
    await db.storeTemplateBinding.create({ data: { storeId: store.id, templateId: template.id } });
    const suppliers: Supplier[] = [];
    for (const suffix of ['A', 'B', 'X']) suppliers.push(await db.supplier.create({ data: { code: `${prefix}${suffix}`, name: suffix, deliveryMode: 'SELF', defaultSettlementMode: 'COMPANY_TERM', defaultSettlementCycle: 'MONTHLY' } }));
    const products: Product[] = [];
    const prices = new Map<string, string>();
    for (const suffix of ['A', 'B']) {
      const product = await db.product.create({ data: { sku: `${prefix}${suffix}`, name: suffix, categoryId: category.id, baseUnitId: unit.id, defaultSalesPrice: '10' } }); products.push(product);
      await db.templateItem.create({ data: { templateId: template.id, productId: product.id, suppliers: { create: suppliers.slice(0, 2).map((supplier, index) => ({ supplierId: supplier.id, priority: index + 1 })) } } });
      for (const [index, supplier] of suppliers.slice(0, 2).entries()) {
        await db.supplierProduct.create({ data: { productId: product.id, supplierId: supplier.id } });
        const scope = await db.priceScope.create({ data: { productId: product.id, supplierId: supplier.id } });
        const price = await db.priceVersion.create({ data: { scopeId: scope.id, salesPrice: index ? '12' : '10', supplyPrice: index ? '9' : '8', effectiveAt: new Date('2026-01-01T00:00:00Z') } });
        prices.set(`${product.id}:${supplier.id}`, price.id);
      }
    }
    const createBody = { storeId: store.id, items: [{ productId: products[0]!.id, quantity: '2' }] };
    const quote = await call('/purchase-requests/preview', 'POST', createBody);
    assert.equal(quote.status, 201); assert.equal(quote.body.data.totals.salesGoodsAmount, '20.00');
    assert.equal(await db.purchaseRequest.count({ where: { storeId: store.id } }), 0);
    assert.equal((await call('/purchase-requests', 'POST', { ...createBody, expectedTemplateId: store.id }, `${prefix}staletemplate`)).status, 409);
    const staleCreate = await call('/purchase-requests', 'POST', { ...createBody, items: [{ ...createBody.items[0], expectedPriceVersionId: prices.get(`${products[0]!.id}:${suppliers[1]!.id}`) }] }, `${prefix}stalecreate`);
    assert.equal(staleCreate.status, 409); assert.equal(await db.purchaseRequest.count({ where: { storeId: store.id } }), 0);
    const created = await call('/purchase-requests', 'POST', createBody, `${prefix}create`); assert.equal(created.status, 201);
    const request = created.body.data;
    const edit = { expectedVersion: request.version, reason: 'Draft edit', items: products.map(product => ({ productId: product.id, supplierId: suppliers[0]!.id, quantity: '3', unitId: unit.id })) };
    const editPreview = await call(`/purchase-requests/${request.id}/items-preview`, 'POST', edit);
    assert.equal(editPreview.status, 201); assert.equal(editPreview.body.data.totals.salesGoodsAmount, '60.00');
    assert.equal((await db.purchaseRequest.findUniqueOrThrow({ where: { id: request.id } })).version, request.version);
    const expectedItems = editPreview.body.data.items.map((item: any, index: number) => ({ ...edit.items[index], expectedPriceVersionId: item.priceVersionId, expectedSupplyPriceVersionId: item.supplyPriceVersionId }));
    const edited = await call(`/purchase-requests/${request.id}/items`, 'PATCH', { ...edit, items: expectedItems }, `${prefix}edit`);
    assert.equal(edited.status, 200); assert.equal(edited.body.data.salesGoodsAmount, '60.00');
    const replayEdit = await call(`/purchase-requests/${request.id}/items`, 'PATCH', { ...edit, items: expectedItems }, `${prefix}edit`);
    assert.equal(replayEdit.status, 200); assert.deepEqual(replayEdit.body.data, edited.body.data);
    assert.equal(await db.auditLog.count({ where: { actorUserId: user.id, action: 'purchase-request.items.replace' } }), 1);
    assert.equal((await db.auditLog.findFirstOrThrow({ where: { actorUserId: user.id, action: 'purchase-request.items.replace' } })).reason, 'Draft edit');
    const changed = edited.body.data;
    const assignment = { expectedVersion: changed.version, supplierId: suppliers[1]!.id, itemIds: changed.items.map((item: any) => item.id) };
    const ineligible = await call(`/purchase-requests/${request.id}/reassign-preview`, 'POST', { ...assignment, supplierId: suppliers[2]!.id });
    assert.equal(ineligible.status, 201); assert.ok(ineligible.body.data.items.every((item: any) => !item.eligible));
    const rejected = await call(`/purchase-requests/${request.id}/assign`, 'POST', { ...assignment, supplierId: suppliers[2]!.id }, `${prefix}rejected`);
    assert.equal(rejected.status, 409);
    assert.equal((await call(`/purchase-requests/${request.id}/assign`, 'POST', { ...assignment, supplierId: suppliers[2]!.id }, `${prefix}rejected`)).status, 409);
    const assignmentPreview = await call(`/purchase-requests/${request.id}/reassign-preview`, 'POST', assignment);
    assert.ok(assignmentPreview.body.data.items.every((item: any) => item.eligible));
    const approved = assignmentPreview.body.data.items.map((item: any) => ({ requestItemId: item.requestItemId, priceVersionId: item.priceVersionId, supplyPriceVersionId: item.supplyPriceVersionId }));
    const changedScope = await db.priceScope.findUniqueOrThrow({ where: { productId_supplierId_templateKey: { productId: products[0]!.id, supplierId: suppliers[1]!.id, templateKey: '' } } });
    await db.priceVersion.create({ data: { scopeId: changedScope.id, salesPrice: '13', supplyPrice: '9', effectiveAt: new Date(Date.now() - 1000), revision: 2 } });
    assert.equal((await call(`/purchase-requests/${request.id}/assign`, 'POST', { ...assignment, expectedPrices: approved }, `${prefix}outdated`)).status, 409);
    const wrongPrices = approved.map((item: any) => ({ ...item, supplyPriceVersionId: prices.get(`${products[0]!.id}:${suppliers[0]!.id}`) }));
    assert.equal((await call(`/purchase-requests/${request.id}/assign`, 'POST', { ...assignment, expectedPrices: wrongPrices }, `${prefix}staleassign`)).status, 409);
    assert.equal((await call(`/purchase-requests/${request.id}/assign`, 'POST', { ...assignment, expectedPrices: [] })).status, 400);
    const refreshed = (await call(`/purchase-requests/${request.id}/reassign-preview`, 'POST', assignment)).body.data;
    const currentPrices = refreshed.items.map((item: any) => ({ requestItemId: item.requestItemId, priceVersionId: item.priceVersionId, supplyPriceVersionId: item.supplyPriceVersionId }));
    const assigned = await call(`/purchase-requests/${request.id}/assign`, 'POST', { ...assignment, expectedPrices: currentPrices }, `${prefix}assign`);
    assert.equal(assigned.status, 201); assert.equal(assigned.body.data.salesGoodsAmount, '75.00');
    assert.ok(assigned.body.data.items.every((item: any) => item.supplierId === suppliers[1]!.id));
    assert.deepEqual((await call(`/purchase-requests/${request.id}/assign`, 'POST', { ...assignment, expectedPrices: currentPrices }, `${prefix}assign`)).body.data, assigned.body.data);
    assert.equal(await db.auditLog.count({ where: { actorUserId: user.id, action: 'purchase-request.assign' } }), 1);
    assert.equal((await call(`/purchase-requests/${request.id}/items`, 'PATCH', edit, `${prefix}conflict`)).status, 409);
    const currentEdit = { ...edit, expectedVersion: assigned.body.data.version, items: [{ ...edit.items[0], expectedSupplyPriceVersionId: prices.get(`${products[0]!.id}:${suppliers[1]!.id}`) }] };
    assert.equal((await call(`/purchase-requests/${request.id}/items`, 'PATCH', currentEdit, `${prefix}staleedit`)).status, 409);
    const processBody = { ...assignment, expectedVersion: assigned.body.data.version };
    await db.commandRecord.create({ data: { actorUserId: user.id, action: 'purchase-request.assign', idempotencyKey: `${prefix}processing`, requestHash: (await import('../../packages/domain/src/idempotency.js')).requestHash({ id: request.id, ...processBody }), traceId: prefix, expiresAt: new Date(Date.now() + 60000) } });
    const processing = await call(`/purchase-requests/${request.id}/assign`, 'POST', processBody, `${prefix}processing`);
    assert.equal(processing.status, 409); assert.equal(processing.body.code, 'COMMAND_PROCESSING');
    assert.equal((await db.purchaseRequest.findUniqueOrThrow({ where: { id: request.id } })).version, assigned.body.data.version);
    const repair = (await call('/purchase-requests', 'POST', { storeId: store.id, items: products.map(product => ({ productId: product.id, quantity: '2' })) }, `${prefix}repaircreate`)).body.data;
    const alternative = await db.orderTemplate.create({ data: { code: `${prefix}ALT`, name: 'New binding' } });
    await db.storeTemplateBinding.updateMany({ where: { storeId: store.id, expiredAt: null }, data: { expiredAt: new Date() } });
    await db.storeTemplateBinding.create({ data: { storeId: store.id, templateId: alternative.id } });
    await db.product.update({ where: { id: products[1]!.id }, data: { isActive: false } });
    await db.supplier.update({ where: { id: suppliers[0]!.id }, data: { status: 'DISABLED' } });
    const editCatalog = await call(`/purchase-requests/${repair.id}/edit-catalog`);
    assert.equal(editCatalog.status, 200); assert.equal(editCatalog.body.data.templateId, template.id);
    assert.equal(editCatalog.body.data.items.length, 1);
    assert.deepEqual(editCatalog.body.data.items[0].suppliers.map((supplier: any) => supplier.supplierId), [suppliers[1]!.id]);
    assert.equal((await call(`/stores/${store.id}/catalog`)).body.data.templateId, alternative.id);
    const repairedBody = { expectedVersion: repair.version, reason: 'Replace invalid original configuration', items: [{ productId: products[0]!.id, supplierId: suppliers[1]!.id, quantity: '2', unitId: unit.id }] };
    const repairQuote = await call(`/purchase-requests/${repair.id}/items-preview`, 'POST', repairedBody);
    assert.equal(repairQuote.status, 201); assert.equal(repairQuote.body.data.templateId, template.id);
    const repaired = await call(`/purchase-requests/${repair.id}/items`, 'PATCH', repairedBody, `${prefix}repair`);
    assert.equal(repaired.status, 200); assert.equal(repaired.body.data.items.length, 1); assert.equal(repaired.body.data.templateId, template.id);
    assert.equal((await db.purchaseRequest.findUniqueOrThrow({ where: { id: repair.id } })).templateId, template.id);
    await db.orderTemplate.update({ where: { id: template.id }, data: { isArchived: true } });
    assert.equal((await call(`/purchase-requests/${repair.id}/edit-catalog`)).status, 404);
    await db.orderTemplate.update({ where: { id: template.id }, data: { isArchived: false } });
    const rejectBody = { expectedVersion: repaired.body.data.version, reason: 'Original configuration cannot be retained' };
    const staleReject = { ...rejectBody, expectedVersion: rejectBody.expectedVersion + 1 };
    assert.equal((await call(`/purchase-requests/${repair.id}/reject`, 'POST', staleReject, `${prefix}failedreject`)).status, 409);
    assert.equal((await call(`/purchase-requests/${repair.id}/reject`, 'POST', staleReject, `${prefix}failedreject`)).status, 409);
    assert.equal((await db.commandRecord.findFirstOrThrow({ where: { actorUserId: user.id, action: 'purchase-request.reject', idempotencyKey: `${prefix}failedreject` } })).status, 'FAILED');
    const cancelled = await call(`/purchase-requests/${repair.id}/reject`, 'POST', rejectBody, `${prefix}reject`);
    assert.equal(cancelled.status, 201); assert.equal(cancelled.body.data.status, 'CANCELED');
    assert.deepEqual((await call(`/purchase-requests/${repair.id}/reject`, 'POST', rejectBody, `${prefix}reject`)).body.data, cancelled.body.data);
    assert.equal(await db.auditLog.count({ where: { entityId: repair.id, action: 'purchase-request.reject' } }), 1);
    await db.product.update({ where: { id: products[1]!.id }, data: { isActive: true } });
    await db.supplier.update({ where: { id: suppliers[0]!.id }, data: { status: 'ACTIVE' } });
    const confirm = await call(`/purchase-requests/${request.id}/confirm`, 'POST', { expectedVersion: assigned.body.data.version }, `${prefix}confirm`);
    assert.equal(confirm.status, 201); assert.equal(await db.supplierOrder.count({ where: { requestId: request.id } }), 1);
    assert.equal((await call(`/purchase-requests/${request.id}/edit-catalog`)).status, 409);
    assert.equal((await call('/purchase-requests/not-a-uuid/edit-catalog')).status, 400);
    assert.equal((await call(`/purchase-requests/${request.id}/items-preview`, 'POST', { ...edit, expectedVersion: assigned.body.data.version + 1 })).status, 409);
    const supplierRole = await db.role.upsert({ where: { code: 'SUPPLIER' }, update: {}, create: { code: 'SUPPLIER', name: 'Supplier' } });
    const supplierUser = await db.user.create({ data: { username: `${prefix}SUPPLIER`, displayName: 'Supplier fixture', passwordHash: await hashPassword('correct-password'), roles: { create: { roleId: supplierRole.id } } } });
    const supplierLogin = await fetch(`${base}/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username: supplierUser.username, password: 'correct-password', client: 'WEB' }) });
    assert.equal(supplierLogin.status, 201);
    const supplierToken = (await supplierLogin.json() as any).data.accessToken;
    const supplierGet = async (path: string) => {
      const response = await fetch(`${base}${path}`, { headers: { authorization: `Bearer ${supplierToken}` } });
      return { status: response.status, body: await response.json() as any };
    };
    assert.equal((await supplierGet(`/purchase-requests/${repair.id}/edit-catalog`)).status, 403);
    for (const path of ['/supplier-orders', '/discrepancies', '/payment-records']) {
      const denied = await supplierGet(path); assert.equal(denied.status, 403); assert.equal(denied.body.code, 'SCOPE_REQUIRED');
    }
    await db.userScope.create({ data: { userId: supplierUser.id, scopeType: 'SUPPLIER', supplierId: suppliers[1]!.id } });
    const order = await db.supplierOrder.findFirstOrThrow({ where: { requestId: request.id } });
    const supplierDetail = await supplierGet(`/supplier-orders/${order.id}`); assert.equal(supplierDetail.status, 200);
    assert.equal(supplierDetail.body.data.salesGoodsAmount, undefined);
    for (const item of supplierDetail.body.data.items) {
      assert.equal(item.salesUnitPrice, undefined); assert.equal(item.salesLineAmount, undefined);
      assert.equal(item.salesPriceVersionId, undefined); assert.equal(item.purchaseSalesUnitPrice, undefined);
      assert.equal(item.supplyUnitPrice, '9'); assert.equal(item.remainingToShipQuantity, '3');
    }
    assert.equal((await call(`/supplier-orders/${order.id}`)).body.data.salesGoodsAmount, '75.00');
    assert.equal((await supplierGet('/discrepancies')).status, 200);
    await db.userScope.update({ where: { userId: supplierUser.id }, data: { supplierId: suppliers[0]!.id } });
    assert.equal((await supplierGet(`/supplier-orders/${order.id}`)).status, 404);
    await db.userScope.update({ where: { userId: supplierUser.id }, data: { supplierId: suppliers[1]!.id } });
    const rejectedOrder = await fetch(`${base}/supplier-orders/${order.id}/reject`, { method: 'POST', headers: { authorization: `Bearer ${supplierToken}`, 'content-type': 'application/json', 'idempotency-key': `${prefix}supplierreject` },
      body: JSON.stringify({ expectedVersion: order.version, reason: 'All remaining goods unavailable' }) });
    assert.equal(rejectedOrder.status, 201); await rejectedOrder.json();
    const rejectedRequest = (await call(`/purchase-requests/${request.id}`)).body.data;
    await db.supplier.update({ where: { id: suppliers[0]!.id }, data: { status: 'DISABLED' } });
    const unavailableReallocation = { expectedVersion: rejectedRequest.version, rejectedOrderId: order.id, reason: 'Inactive alternate', assignments: rejectedRequest.items.map((item: any) => ({ requestItemId: item.id, supplierId: suppliers[0]!.id })) };
    assert.equal((await call(`/purchase-requests/${request.id}/reallocate`, 'POST', unavailableReallocation, `${prefix}inactivealternate`)).status, 409);
    assert.equal((await db.purchaseRequest.findUniqueOrThrow({ where: { id: request.id } })).version, rejectedRequest.version);
    assert.equal(await db.supplierOrder.count({ where: { requestId: request.id, status: { not: 'REJECTED' } } }), 0);
    await db.supplier.update({ where: { id: suppliers[0]!.id }, data: { status: 'ACTIVE' } });
    const cancellationBody = { expectedVersion: rejectedRequest.version, rejectedOrderId: order.id, reason: 'Cancel all rejected products', assignments: rejectedRequest.items.map((item: any) => ({ requestItemId: item.id, cancel: true })) };
    const cancellation = await call(`/purchase-requests/${request.id}/reallocate`, 'POST', cancellationBody, `${prefix}cancelall`);
    assert.equal(cancellation.status, 201); assert.equal(cancellation.body.data.status, 'CANCELED'); assert.equal(cancellation.body.data.items.length, 0);
    assert.deepEqual((await call(`/purchase-requests/${request.id}/reallocate`, 'POST', cancellationBody, `${prefix}cancelall`)).body.data, cancellation.body.data);
    assert.equal(await db.auditLog.count({ where: { entityId: request.id, action: 'purchase-request.reallocate' } }), 1);
    assert.equal(await db.supplierOrder.count({ where: { requestId: request.id, status: { not: 'REJECTED' } } }), 0);
    assert.equal((await db.supplierOrder.findUniqueOrThrow({ where: { id: order.id } })).status, 'REJECTED');
  } finally {
    await app.close();
    await db.commandRecord.deleteMany({ where: { actor: { username: { startsWith: prefix } } } });
    await db.userScope.deleteMany({ where: { user: { username: { startsWith: prefix } } } });
    await db.user.deleteMany({ where: { username: { startsWith: prefix } } });
    await db.fundingAllocation.deleteMany({ where: { store: { store: { code: prefix } } } });
    await db.supplierOrder.deleteMany({ where: { store: { code: prefix } } });
    await db.purchaseRequest.deleteMany({ where: { store: { code: prefix } } });
    await db.accountLedger.deleteMany({ where: { account: { store: { code: prefix } } } });
    await db.storeAccount.deleteMany({ where: { store: { code: prefix } } });
    await db.storeTemplateBinding.deleteMany({ where: { template: { code: { startsWith: prefix } } } });
    await db.templateItemSupplier.deleteMany({ where: { templateItem: { template: { code: prefix } } } });
    await db.templateItem.deleteMany({ where: { template: { code: prefix } } });
    await db.orderTemplate.deleteMany({ where: { code: { startsWith: prefix } } });
    const products = await db.product.findMany({ where: { sku: { startsWith: prefix } }, select: { id: true } });
    await db.priceVersion.deleteMany({ where: { scope: { productId: { in: products.map(product => product.id) } } } });
    await db.priceScope.deleteMany({ where: { productId: { in: products.map(product => product.id) } } });
    await db.supplierProduct.deleteMany({ where: { supplier: { code: { startsWith: prefix } } } });
    await db.product.deleteMany({ where: { sku: { startsWith: prefix } } });
    await db.supplier.deleteMany({ where: { code: { startsWith: prefix } } });
    await db.store.deleteMany({ where: { code: prefix } });
    await db.category.deleteMany({ where: { code: prefix } }); await db.unit.deleteMany({ where: { code: prefix } });
    await db.$disconnect();
  }
});
