import assert from 'node:assert/strict';
import test from 'node:test';
import { AddressInfo } from 'node:net';
import { NestFactory } from '@nestjs/core';
import { PrismaPg } from '@prisma/adapter-pg';
import { AppModule } from '../../apps/api/src/app.module.js';
import { ApiExceptionFilter } from '../../apps/api/src/common/api-exception.filter.js';
import { ResponseEnvelopeInterceptor } from '../../apps/api/src/common/response-envelope.interceptor.js';
import { PrismaClient } from '../../packages/backend/generated/prisma/client.js';
import { hashPassword } from '../../packages/domain/src/password.js';

test('formal workspace master-data reads are authorized and concurrent edits/bindings cannot overwrite each other', async () => {
  const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL ?? 'postgresql://procurex:procurex_local_only@127.0.0.1:55438/procurex?schema=public' }) });
  const prefix = `ITWEB${Date.now()}`;
  const app = await NestFactory.create(AppModule, { logger: false });
  app.setGlobalPrefix('api/v1'); app.useGlobalFilters(new ApiExceptionFilter()); app.useGlobalInterceptors(new ResponseEnvelopeInterceptor());
  try {
    await app.listen(0, '127.0.0.1');
    const base = `http://127.0.0.1:${(app.getHttpServer().address() as AddressInfo).port}/api/v1`;
    const tokenFor = async (code: string, scope?: { scopeType: 'STORE' | 'SUPPLIER'; storeId?: string; supplierId?: string }) => {
      const role = await db.role.upsert({ where: { code }, update: {}, create: { code, name: code } });
      const username = `${prefix}${code}${scope ? 'SCOPED' : ''}`;
      await db.user.create({ data: { username, displayName: code, passwordHash: await hashPassword('correct-password'), roles: { create: { roleId: role.id } }, ...(scope ? { scopes: { create: scope } } : {}) } });
      const response = await fetch(`${base}/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username, password: 'correct-password', client: 'WEB' }) });
      assert.equal(response.status, 201); return (await response.json() as any).data.accessToken as string;
    };
    const admin = await tokenFor('ADMIN'), finance = await tokenFor('HQ_FINANCE'), supplierToken = await tokenFor('SUPPLIER');
    const call = async (path: string, method = 'GET', body?: object, token = admin) => {
      const response = await fetch(`${base}${path}`, { method, headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' }, body: body ? JSON.stringify(body) : undefined });
      return { status: response.status, body: await response.json() as any };
    };
    assert.equal((await call('/stores', 'POST', { code: prefix, name: 'Incomplete store' })).status, 400);
    assert.equal((await call('/suppliers', 'POST', { code: prefix, name: 'Incomplete supplier', deliveryMode: 'SELF', defaultSettlementMode: 'COMPANY_TERM', defaultSettlementCycle: 'HALF_MONTHLY' })).status, 400);
    assert.equal((await call('/store-groups', 'POST', { name: `${prefix}East` })).status, 201);
    const storeResult = await call('/stores', 'POST', { code: prefix, name: 'Workspace store', contactName: 'Store contact', contactPhone: '13800000000', address: 'Store address', storeType: 'FRANCHISE', groupName: `${prefix}East`, receiptAddress: 'Warehouse address', receiptContactName: 'Warehouse contact', receiptContactPhone: '13900000000' });
    assert.equal(storeResult.status, 201);
    const store = storeResult.body.data;
    assert.equal(store.storeType, 'FRANCHISE'); assert.equal(store.receiptAddress, 'Warehouse address');
    assert.equal((await call(`/stores/${store.id}`, 'PATCH', { expectedVersion: store.version, receiptAddress: 'Partial address' })).status, 400);
    assert.equal((await call(`/stores/${store.id}`, 'PATCH', { expectedVersion: store.version, storeType: 'OTHER' })).status, 400);
    assert.equal((await call(`/stores/${store.id}`, 'PATCH', { expectedVersion: store.version, address: null })).status, 400);
    const supplierResult = await call('/suppliers', 'POST', { code: prefix, name: 'Workspace supplier', deliveryMode: 'SELF', defaultSettlementMode: 'COMPANY_TERM', defaultSettlementCycle: 'HALF_MONTHLY', contactName: 'Supplier contact', contactPhone: '13900000000', address: 'Supplier address', bankName: 'Bank', bankAccountName: 'Supplier', bankAccount: '001234', taxpayerId: 'TEST-TAX', invoiceTitle: 'Supplier', supplierType: 'HEADQUARTERS', settlementCycleDescription: 'Natural half month', remark: 'Test profile' });
    assert.equal(supplierResult.body.data.code, prefix);
    const autoBody = { ...supplierResult.body.data, name: `${prefix}自动供应商` }; delete autoBody.code;
    const automatic = await Promise.all([call('/suppliers', 'POST', autoBody), call('/suppliers', 'POST', autoBody)]);
    for (const result of automatic) { assert.equal(result.status, 201); assert.match(result.body.data.code, /^GYS[A-F0-9]{32}$/); }
    assert.notEqual(automatic[0].body.data.code, automatic[1].body.data.code);
    for (const code of ['', ' ', null, 123, 'X'.repeat(81)]) assert.equal((await call('/suppliers', 'POST', { ...autoBody, code })).status, 400);
    assert.equal(supplierResult.status, 201);
    const supplier = supplierResult.body.data;
    assert.equal(supplier.bankAccount, '001234'); assert.equal(supplier.requiresFreight, false);
    assert.equal((await call(`/suppliers/${supplier.id}`, 'PATCH', { expectedVersion: supplier.version, bankAccount: null })).status, 400);
    assert.equal((await call(`/suppliers/${supplier.id}`, 'PATCH', { expectedVersion: supplier.version, requiresFreight: 'false' })).status, 400);
    assert.equal((await call(`/suppliers/${supplier.id}`, 'PATCH', { expectedVersion: supplier.version, defaultSettlementCycle: 'CUSTOM' })).status, 400);
    const oldStore = await db.store.create({ data: { code: `${prefix}OLD`, name: 'Legacy incomplete store' } });
    const oldSupplier = await db.supplier.create({ data: { code: `${prefix}OLD`, name: 'Legacy incomplete supplier', deliveryMode: 'SELF', defaultSettlementMode: 'COMPANY_TERM', defaultSettlementCycle: 'MONTHLY' } });
    const oldStoreEdit = await call(`/stores/${oldStore.id}`, 'PATCH', { expectedVersion: oldStore.updatedAt.getTime(), status: 'DISABLED' });
    assert.equal(oldStoreEdit.status, 200); assert.equal(oldStoreEdit.body.data.storeType, null); assert.equal(oldStoreEdit.body.data.receiptAddress, null);
    const oldSupplierEdit = await call(`/suppliers/${oldSupplier.id}`, 'PATCH', { expectedVersion: oldSupplier.updatedAt.getTime(), remark: 'Legacy remains incomplete' });
    assert.equal(oldSupplierEdit.status, 200); assert.equal(oldSupplierEdit.body.data.bankAccount, null); assert.equal(oldSupplierEdit.body.data.requiresFreight, null);
    const category = await db.category.create({ data: { code: prefix, name: 'Workspace category' } });
    const unit = await db.unit.create({ data: { code: prefix, name: 'piece' } });
    const product = (await call('/products', 'POST', { sku: prefix, name: 'Workspace product', defaultSalesPrice: '10', categoryId: category.id, baseUnitId: unit.id })).body.data;
    assert.equal((await call(`/suppliers/${supplier.id}/products`, 'GET', undefined, supplierToken)).status, 403);
    assert.equal((await call(`/suppliers/${supplier.id}/products`, 'GET', undefined, finance)).status, 200);
    assert.equal((await call(`/suppliers/${supplier.id}/products`, 'PUT', { expectedVersion: supplier.version, productIds: [] }, finance)).status, 403);
    const related = await call(`/suppliers/${supplier.id}/products`, 'PUT', { expectedVersion: supplier.version, productIds: [product.id] });
    assert.equal(related.status, 200); assert.ok(related.body.data.version > supplier.version);
    assert.deepEqual((await call(`/suppliers/${supplier.id}/products`)).body.data.productIds, [product.id]);
    const ownSupplier = await tokenFor('SUPPLIER', { scopeType: 'SUPPLIER', supplierId: supplier.id });
    const ownStore = await tokenFor('STORE', { scopeType: 'STORE', storeId: store.id });
    const unscopedStore = await tokenFor('STORE');
    assert.equal((await call(`/suppliers/${supplier.id}`, 'GET', undefined, supplierToken)).status, 403);
    assert.equal((await call(`/suppliers/${supplier.id}/catalog`, 'GET', undefined, supplierToken)).status, 403);
    assert.equal((await call(`/stores/${store.id}`, 'GET', undefined, unscopedStore)).status, 403);
    assert.equal((await call(`/stores/${store.id}`, 'GET', undefined, ownStore)).body.data.receiptAddress, 'Warehouse address');
    assert.equal((await call(`/stores/${oldStore.id}`, 'GET', undefined, ownStore)).status, 403);
    assert.equal((await call(`/suppliers/${oldSupplier.id}`, 'GET', undefined, ownSupplier)).status, 403);
    assert.equal((await call(`/suppliers/${oldSupplier.id}/catalog`, 'GET', undefined, ownSupplier)).status, 403);
    assert.equal((await call(`/suppliers/${supplier.id}`, 'GET', undefined, ownSupplier)).body.data.bankAccount, '001234');
    const ownCatalog = (await call(`/suppliers/${supplier.id}/catalog`, 'GET', undefined, ownSupplier)).body.data;
    assert.deepEqual(ownCatalog.items.map((item: any) => item.id), [product.id]);
    assert.equal(ownCatalog.items[0].supplyPrice, null);
    assert.deepEqual(Object.keys(ownCatalog.items[0]).sort(), ['id', 'isActive', 'name', 'sku', 'specification', 'supplyPrice', 'supplyPriceVersionId', 'unitName']);
    assert.equal((await call(`/suppliers/${supplier.id}`, 'PATCH', { expectedVersion: related.body.data.version, name: 'Forbidden' }, ownSupplier)).status, 403);
    assert.equal((await call('/products', 'GET', undefined, ownSupplier)).status, 403);
    assert.equal((await call(`/suppliers/${supplier.id}/products`, 'PUT', { expectedVersion: supplier.version, productIds: [] })).status, 409);
    const supplierVersion = related.body.data.version;
    const supplierEdits = await Promise.all(['A', 'B'].map(name => call(`/suppliers/${supplier.id}`, 'PATCH', { expectedVersion: supplierVersion, name })));
    assert.deepEqual(supplierEdits.map(result => result.status).sort(), [200, 409]);
    const storeEdits = await Promise.all(['A', 'B'].map(name => call(`/stores/${store.id}`, 'PATCH', { expectedVersion: store.version, name })));
    assert.deepEqual(storeEdits.map(result => result.status).sort(), [200, 409]);
    const templates = [];
    for (const suffix of ['A', 'B']) templates.push((await call('/templates', 'POST', { code: `${prefix}${suffix}`, name: `${prefix} Workspace ${suffix}`, tag: 'Workspace', remark: 'Source remark' })).body.data);
    assert.equal((await call(`/templates/${templates[0].id}/supplier-settings/${supplier.id}`, 'PUT', { expectedVersion: templates[0].version, settlementMode: 'COMPANY_TERM', settlementCycle: 'MONTHLY' })).status, 409);
    assert.equal((await call(`/templates/${templates[0].id}/supplier-settings/${supplier.id}`, 'PUT', { expectedVersion: templates[0].version, settlementMode: 'COMPANY_TERM', settlementCycle: 'CUSTOM' })).status, 400);
    const bindings = await Promise.all(templates.map(template => call(`/templates/${template.id}/stores`, 'PUT', { expectedVersion: template.version, storeIds: [store.id] })));
    assert.deepEqual(bindings.map(result => result.status).sort(), [200, 409]);
    assert.equal(await db.storeTemplateBinding.count({ where: { storeId: store.id, expiredAt: null } }), 1);
    const template = (await call(`/templates/${templates[bindings.findIndex(result => result.status === 200)]!.id}`)).body.data;
    assert.deepEqual(template.storeIds, [store.id]);
    assert.equal((await call(`/templates/${template.id}`, 'GET', undefined, finance)).status, 403);
    assert.equal((await call(`/templates/${template.id}`, 'GET', undefined, supplierToken)).status, 403);
    const itemWrites = await Promise.all([10, 20].map(priority => call(`/templates/${template.id}/items`, 'PUT', {
      expectedVersion: template.version, items: [{ productId: product.id, sortOrder: 0, suppliers: [{ supplierId: supplier.id, priority }] }],
    })));
    assert.deepEqual(itemWrites.map(result => result.status).sort(), [200, 409]);
    const detail = (await call(`/templates/${template.id}`)).body.data;
    assert.equal(detail.items.length, 1); assert.equal(detail.items[0].suppliers.length, 1); assert.ok(detail.version > template.version);
    const setting = await call(`/templates/${template.id}/supplier-settings/${supplier.id}`, 'PUT', { expectedVersion: detail.version, settlementMode: 'COMPANY_TERM', settlementCycle: 'MONTHLY' });
    assert.equal(setting.status, 200);
    assert.equal((await call(`/templates/${template.id}`)).body.data.settings[0].settlementCycle, 'MONTHLY');
    assert.equal((await call(`/templates/${template.id}/items`, 'PUT', { expectedVersion: detail.version, items: [] })).status, 409);
    const legacyRequest = await db.purchaseRequest.create({ data: { requestNo: `${prefix}PR`, storeId: store.id, templateId: template.id, status: 'CONFIRMED', submittedAt: new Date('2026-10-03T01:00:00Z') } });
    const legacyOrder = await db.supplierOrder.create({ data: { supplierOrderNo: `${prefix}SO`, requestId: legacyRequest.id, storeId: store.id, supplierId: supplier.id,
      settlementMode: 'COMPANY_TERM', settlementCycleSnapshot: 'MONTHLY', salesGoodsAmount: '20', supplyGoodsAmount: '16',
      items: { create: { productId: product.id, quantity: '2', salesUnitPrice: '10', supplyUnitPrice: '8', salesLineAmount: '20', supplyLineAmount: '16' } } } });
    const orderDetail = (await call(`/supplier-orders/${legacyOrder.id}`)).body.data;
    assert.equal(orderDetail.destination.address, 'Warehouse address');
    assert.equal(orderDetail.destination.contactName, 'Warehouse contact');
    const currentStore = (await call('/stores')).body.data.find((row: any) => row.id === store.id);
    const resetReceipt = await call(`/stores/${store.id}`, 'PATCH', { expectedVersion: currentStore.version, receiptAddress: null, receiptContactName: null, receiptContactPhone: null });
    assert.equal(resetReceipt.status, 200);
    assert.equal((await call(`/supplier-orders/${legacyOrder.id}`)).body.data.destination.address, 'Store address');
    assert.equal((await db.supplierOrder.findUniqueOrThrow({ where: { id: legacyOrder.id } })).requiresFreightSnapshot, null);
    const firstPrice = await call('/prices/impact-preview', 'POST', { productId: product.id, supplierId: supplier.id, salesPrice: '12', supplyPrice: '10', effectiveAt: '2026-10-03T00:00:00Z' });
    assert.equal(firstPrice.status, 201); assert.equal(firstPrice.body.data.scopeId, ''); assert.equal(firstPrice.body.data.affectedOrderCount, 1);
    assert.equal(firstPrice.body.data.salesDelta, '4.00'); assert.equal(firstPrice.body.data.supplyDelta, '4.00');
    assert.equal(firstPrice.body.data.orders[0].supplierOrderId, legacyOrder.id);
    assert.equal((await db.supplierOrder.findUniqueOrThrow({ where: { id: legacyOrder.id } })).salesGoodsAmount.toFixed(2), '20.00');
    assert.equal(await db.priceVersion.count({ where: { scope: { productId: product.id } } }), 0);
    const supplierBeforeClear = (await call('/suppliers')).body.data.find((row: any) => row.id === supplier.id);
    assert.equal((await call('/suppliers', 'GET', undefined, finance)).body.data.find((row: any) => row.id === supplier.id).bankAccount, '001234');
    const clearedOptional = await call(`/suppliers/${supplier.id}`, 'PATCH', { expectedVersion: supplierBeforeClear.version, supplierType: null, remark: null, settlementCycleDescription: null });
    assert.equal(clearedOptional.status, 200); assert.equal(clearedOptional.body.data.remark, null);
    assert.equal(clearedOptional.body.data.bankAccount, '001234'); assert.equal(clearedOptional.body.data.requiresFreight, false);
    assert.equal((await call('/templates', 'POST', { code: `${prefix}MISSING`, name: 'Missing tag' })).status, 400);
    const names = await Promise.all(['D', 'E'].map(suffix => call('/templates', 'POST', { code: `${prefix}${suffix}`, name: `${prefix} Duplicate name`, tag: 'Duplicate' })));
    assert.deepEqual(names.map(result => result.status).sort(), [201, 409]);
    const current = (await call(`/templates/${template.id}`)).body.data;
    const renamed = await call(`/templates/${template.id}`, 'PATCH', { expectedVersion: current.version, name: `${prefix} Renamed`, tag: 'Edited', remark: 'Edited remark' });
    assert.equal(renamed.status, 200); assert.ok(renamed.body.data.version > current.version);
    assert.equal((await call(`/templates/${template.id}/copy`, 'POST', { expectedVersion: current.version, code: `${prefix}COPY`, name: `${prefix} Copy`, tag: 'Edited' })).status, 409);
    assert.equal((await call(`/templates/${template.id}/copy`, 'POST', { expectedVersion: renamed.body.data.version, code: `${prefix}COPY`, name: `${prefix} Copy`, tag: 'Edited' }, finance)).status, 403);
    const copy = await call(`/templates/${template.id}/copy`, 'POST', { expectedVersion: renamed.body.data.version, code: `${prefix}COPY`, name: `${prefix} Copy`, tag: 'Edited' });
    assert.equal(copy.status, 201);
    const copied = (await call(`/templates/${copy.body.data.id}`)).body.data;
    assert.equal(copied.items[0].initialSalesPrice, '10');
    assert.deepEqual(copied.storeIds, []); assert.deepEqual(copied.items, current.items); assert.deepEqual(copied.settings, current.settings);
    assert.equal(copied.remark, 'Edited remark');
    const defaults = await call(`/templates/${copied.id}/supplier-settings/${supplier.id}`, 'DELETE', { expectedVersion: copied.version });
    assert.equal(defaults.status, 200); assert.equal(defaults.body.data.usesDefault, true); assert.equal(defaults.body.data.settlementCycle, 'HALF_MONTHLY');
    assert.equal((await call(`/templates/${copied.id}`)).body.data.settings.length, 0);
    assert.equal((await call(`/templates/${copied.id}/supplier-settings/${supplier.id}`, 'DELETE', { expectedVersion: copied.version })).status, 409);
    const archived = await call(`/templates/${template.id}/archive`, 'POST', { expectedVersion: renamed.body.data.version });
    assert.equal(archived.status, 201); assert.equal(archived.body.data.isArchived, true);
    assert.equal(await db.storeTemplateBinding.count({ where: { templateId: template.id, expiredAt: null } }), 0);
    assert.equal(await db.templateItem.count({ where: { templateId: template.id } }), 0);
    assert.equal(await db.templateSupplierSetting.count({ where: { templateId: template.id } }), 0);
    assert.equal((await db.supplierOrder.findUniqueOrThrow({ where: { id: legacyOrder.id } })).salesGoodsAmount.toFixed(2), '20.00');
    assert.equal((await db.purchaseRequest.findUniqueOrThrow({ where: { id: legacyRequest.id } })).templateId, template.id);
    assert.equal((await call(`/templates/${template.id}/stores`, 'PUT', { expectedVersion: archived.body.data.version, storeIds: [store.id] })).status, 404);
    const copiedCurrent = (await call(`/templates/${copied.id}`)).body.data;
    assert.equal((await call(`/templates/${copied.id}/stores`, 'PUT', { expectedVersion: copiedCurrent.version, storeIds: [store.id] })).status, 200);
    assert.equal(await db.priceVersion.count({ where: { scope: { productId: product.id } } }), 0);
    const beforeArchive = (await call(`/suppliers/${supplier.id}`)).body.data;
    const preservedScope = await db.priceScope.create({ data: { productId: product.id, supplierId: supplier.id } });
    const preservedPrice = await db.priceVersion.create({ data: { scopeId: preservedScope.id, salesPrice: '12', supplyPrice: '10', effectiveAt: new Date('2026-01-01T00:00:00Z'), revision: 1, reason: 'Archive retention fixture' } });
    const pricedCatalog = (await call(`/suppliers/${supplier.id}/catalog`, 'GET', undefined, ownSupplier)).body.data;
    assert.equal(pricedCatalog.items[0].supplyPrice, '10');
    assert.equal(pricedCatalog.items[0].supplyPriceVersionId, preservedPrice.id);
    assert.equal('salesPrice' in pricedCatalog.items[0], false);
    assert.equal((await call(`/suppliers/${supplier.id}/archive`, 'POST', { expectedVersion: beforeArchive.version }, ownSupplier)).status, 403);
    assert.equal((await call(`/suppliers/${supplier.id}/archive`, 'POST', { expectedVersion: supplier.version })).status, 409);
    const supplierArchived = await call(`/suppliers/${supplier.id}/archive`, 'POST', { expectedVersion: beforeArchive.version });
    assert.equal(supplierArchived.status, 201); assert.equal(supplierArchived.body.data.isArchived, true);
    assert.equal(await db.supplierProduct.count({ where: { supplierId: supplier.id } }), 0);
    assert.equal(await db.templateItemSupplier.count({ where: { supplierId: supplier.id } }), 0);
    assert.equal(await db.templateSupplierSetting.count({ where: { supplierId: supplier.id } }), 0);
    assert.equal((await db.priceVersion.findUniqueOrThrow({ where: { id: preservedPrice.id } })).supplyPrice.toString(), '10');
    assert.equal((await db.supplierOrder.findUniqueOrThrow({ where: { id: legacyOrder.id } })).salesGoodsAmount.toFixed(2), '20.00');
    assert.equal((await call(`/suppliers/${supplier.id}/catalog`, 'GET', undefined, ownSupplier)).body.data.items.length, 0);
    assert.equal((await call(`/suppliers/${supplier.id}`, 'GET', undefined, ownSupplier)).body.data.bankAccount, '001234');
    assert.equal((await call(`/suppliers/${supplier.id}`, 'PATCH', { expectedVersion: supplierArchived.body.data.version, status: 'ACTIVE' })).status, 409);
    assert.equal((await call(`/suppliers/${supplier.id}/products`, 'PUT', { expectedVersion: supplierArchived.body.data.version, productIds: [product.id] })).status, 409);
    const afterArchiveTemplate = (await call(`/templates/${copied.id}`)).body.data;
    assert.ok(afterArchiveTemplate.version > copiedCurrent.version);
    assert.equal((await call(`/templates/${copied.id}/items`, 'PUT', { expectedVersion: afterArchiveTemplate.version, items: [{ productId: product.id, suppliers: [{ supplierId: supplier.id, priority: 1 }] }] })).status, 404);
  } finally {
    await app.close();
    await db.user.deleteMany({ where: { username: { startsWith: prefix } } });
    await db.supplierOrder.deleteMany({ where: { supplierOrderNo: `${prefix}SO` } });
    await db.purchaseRequest.deleteMany({ where: { requestNo: `${prefix}PR` } });
    await db.storeTemplateBinding.deleteMany({ where: { template: { code: { startsWith: prefix } } } });
    await db.templateSupplierSetting.deleteMany({ where: { template: { code: { startsWith: prefix } } } });
    await db.templateItemSupplier.deleteMany({ where: { templateItem: { template: { code: { startsWith: prefix } } } } });
    await db.templateItem.deleteMany({ where: { template: { code: { startsWith: prefix } } } });
    await db.orderTemplate.deleteMany({ where: { code: { startsWith: prefix } } });
    await db.supplierProduct.deleteMany({ where: { supplier: { code: prefix } } });
    const cleanupProducts = await db.product.findMany({ where: { sku: prefix }, select: { id: true } });
    const cleanupProductIds = cleanupProducts.map(product => product.id);
    await db.priceVersion.deleteMany({ where: { scope: { productId: { in: cleanupProductIds } } } });
    await db.priceScope.deleteMany({ where: { productId: { in: cleanupProductIds } } });
    await db.product.deleteMany({ where: { sku: prefix } });
    await db.category.deleteMany({ where: { code: prefix } }); await db.unit.deleteMany({ where: { code: prefix } });
    await db.store.deleteMany({ where: { code: { startsWith: prefix } } }); await db.supplier.deleteMany({ where: { OR: [{ code: { startsWith: prefix } }, { name: `${prefix}自动供应商` }] } });
    await db.storeGroup.deleteMany({ where: { name: { startsWith: prefix } } });
    await db.$disconnect();
  }
});
